# Generated by Django 4.2.7 on 2023-11-24 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True, verbose_name='Название')),
                ('author', models.CharField(max_length=255, verbose_name='Автор')),
                ('year_published', models.PositiveIntegerField(verbose_name='Год издания')),
                ('isbn', models.CharField(max_length=13, verbose_name='ISBN')),
            ],
            options={
                'verbose_name': 'Книга',
                'verbose_name_plural': 'Книги',
            },
        ),
    ]
