# Generated by Django 4.2.7 on 2023-11-24 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newuser',
            name='is_stuff',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='newuser',
            name='email',
            field=models.EmailField(db_index=True, error_messages={'unique': 'Указанный почтовый адрес уже занято.'}, max_length=254, unique=True, verbose_name='Почтовый адрес'),
        ),
        migrations.AlterField(
            model_name='newuser',
            name='user_name',
            field=models.CharField(db_index=True, error_messages={'unique': 'Указанное имя уже занято.'}, max_length=150, unique=True, verbose_name='Имя пользователя'),
        ),
    ]
