# Generated by Django 4.2.7 on 2023-11-24 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_newuser_is_stuff_alter_newuser_email_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newuser',
            old_name='is_stuff',
            new_name='is_staff',
        ),
    ]
